#!/usr/bin/env bash

datagen(){
  ./gen-glyph-list.js
  python3 ./data_gen.py
}

train(){
  # ipython3 --matplotlib=tk train.py -- --traindata ./data/train_data.npz --valdata ./data/validate_data.npz
  python3 train.py --traindata ./data/train_data.npz --valdata ./data/validate_data.npz
}





if [ -z $1 ]; then
  cat<<EOF
Usage:
./pottan <command> [ arguments ]

List of available commands:

    datagen - Prepare training data from data/train.txt & data/validate.txt.

    train   - Run the training
EOF
else
  $1
fi

